using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GoSolve.Tools.Common.Database.Models;

/// <summary>
/// Abstract base class for database entity models which have autogenerated timestamps and an id.
/// </summary>
/// <typeparam name="TId">Type of the id of the entity, ex: long or Guid.</typeparam>
public abstract class BaseEntity<TId> : TimestampedEntity
{
    /// <summary>
    /// The id of the entity.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public TId Id { get; set; }
}

/// <summary>
/// Abstract base class for database entity models which have autogenerated timestamps.
/// </summary>
public abstract class TimestampedEntity
{
    /// <summary>
    /// Creation date of the entity.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Date when the entity was last updated.
    /// </summary>
    public DateTime UpdatedAt { get; set; }
}
